### ISSUE TITLE
Proposal: Two or three update modes

### ISSUE THREAD

**Issue by codemanyak** [fesch/Upla#4]
In order to make it trackable, I summarize some suggestions I had made in #2.
There might be an additional property in upla.ini that specifies one of two or three different update strategies:
- automatic (a differing, i.e. newer, version is automatically downloaded before start);
- automatic search but interactive download commitment (the user will be informed that a new version is available but may decline its download and adhere to the recent version);
- no search for updates.

The third option is not actually desirable from the support perspective but may be sensible with slow network connection or under privacy aspect.

**Comment by fesch** [comment]
I like the idea and will think about it.

A first "problem" I see, is how the user may change it's preferences after the destination application, which is not at all aware of having been launched by Upla, has started. So the only way to do this is in Upla itself an thus during the network check & application launch, which might be very short.

As said, I will think about a solution ...

**Comment by codemanyak** [comment]
> A first "problem" I see, is how the user may change it's preferences after the destination application, which is not at all aware of having been launched by Upla, has started. So the only way to do this is in Upla itself an thus during the network check & application launch, which might be very short.

The application itself is indeed not involved. To keep this in UpLa is indeed what I had in mind. This is the rough sketch:
UpLa.ini contains a property update level (0..3 or "none"/"interactive"/"automatic") which UpLa main checks and then does one of the following:
With all update levels it is to check whether the product jar is present and has to download it if not without any questions. If there is already a downloaded application jar then the update level comes in:
- With level "none" it starts it right away without network check or whatever.
- With level "interactive" it does the md5 check and informs the user if there is a difference. If so it is to present a ConfirmDialog that informs about the availability of a new version, shows the new version number (if available via a URL optionally placed in upla.ini) and an active link to the product homepage for more details and finally a YES/NO button pair for "Do you want to download the new version now?". In case of "YES" UpLa proceeds as in automatic mode (the default), otherwise skips the download and just starts the application.
- With level "automatic", UpLa follows the way of the current implementation.

In order to change the update level, there should be a little executable in the installation directory, say setup.exe for Windows, which can be started over the "Modify" button from the "Programs and Features". Fortunately, the application is now listed there even in case of a user-individual installation, i.e. for the very user. If it should accidently not be available there, then the setup.exe can still be launched directly from the application directory (but may have an access problem, see below).

Could the application itself be aware of being started via UpLa.jar? In a way yes. Structorizer, for example, checks whether there is an UpLa.jar in its application folder (from version 3.29-12 on, in order to suppress its own update check option in analogy to WebStart - this was the most recent change in the bugfix branch if you want to have a look). This is not a bomb-proof test but a plausible one.

What is left? Can the installer offer a choice to the user on installation and place the chosen level in the upla.ini? I think, with a Pascal extension this should be feasible. If not then UpLa itself could check whether the update level is specified in upla.ini and if not ask to set it before or after it starts to check the internet connection. It might invoke the setup.exe for it, because there is of course an issue with the access rights to upla.ini (usually it requires system priviledges, and should do so for good reasons). Hence, setup.exe must acquire administrative privileges via the UAC.

**Comment by fesch** [comment]
All implemented.

**Comment by fesch** [comment]
Right now, the installer does not contain the full features JAR file, but only a dummy replacement (in order to set the rights ...). This means, that the installation does not really install the application, but only sets the frame.

Question: Should the full featured JAR be included (bigger installation file) or not (smaller installation file).

**Comment by fesch** [comment]
The EXE files inside the installer (upla.exe & structorizer.exe) are now also digitally signed.

**Comment by codemanyak** [comment]
> Question: Should the full featured JAR be included (bigger installation file) or not (smaller installation file).

So what are the pros and cons here?
Cons:
- I'd say it would be redundant and consumes additional time.
- The installer would have to be rebuilt every now and then to contain a not too old jar version.

Pros:
- It would make the displayed disk place requirement more realistic. You know: By now it promises only 2.5 MiB, whereas e.g. for Structorizer an extra space of about 7 MiB will be consumed on downloading the true Jar file.
- After having downloaded the installer, the program could be installed offline and got to work (possibly with a somewhat obsolete, but at least functioning version).

So I tend to say: Put a full Jar file into the installer package. The chances aren't bad that the first installation won't have to download a newer version immediately.

**Comment by fesch** [comment]
I was tending towards the same solution ;)
Thanks

**Comment by fesch** [comment]
BTW, running the update settings immediately after the installation is now also integrated

**Comment by mordechaim** [comment]
Hey folks!

I was wondering if [update4j](https://github.com/update4j/update4j) is in any way relevant to solve what this repo tries to.

Update4j is a project of mine where you control the update/launch setup yourself. You can implement an interactive updater, or pre-launch or post-shutdown; it's all up to you.

I was simply doing a github search for Java updaters and found this repo.

**Comment by fesch** [comment]
Thankis @mordechaim, for your clarification. Actually I didn't know about your tool and right now, mine is working fine. But who knows, maybe I'll come back to yours. I will at least check it to see what it can do :-D
