### ISSUE TITLE
Errors on installation

### ISSUE THREAD

**Issue by codemanyak** [fesch/Upla#5]
## Installation "for all users"
When installing Structorizer with the most up-to-date Installer "for all users" then the start of the Structorizer itself (after setting the update mode) fails with the following error message:
![Update_mode_never](https://user-images.githubusercontent.com/15326471/62168067-ee512280-b324-11e9-8cbd-e78229c30db1.png)
Obviously the path encoding again, at different places: I identified methods `getLocalMD5()`, `download()` (where `out.close();` was also misplaced), and `main()` (line `    File jar = new File(program);`).

Some javaw.exe processes remain active after the installation (and desperate attempts to set the update mode via the Modify button in System Control). Their command line is:
```
"C:\Program Files\Java\jre1.8.0_191\bin\javaw.exe" -jar "C:\Program Files (x86)\Structorizer\Upla.jar" /modify=1
```
So it's the modification process, obviously. The property "updateMode" had not been written to the "upla.ini" file, either, on the initial configuration. So it may yet have been an access problem. The modification part had to be put into a try block. After having done the latter, it became indeed clear, that the access to upla.ini is denied when the configuration is instigated by the installer - apparently (and not surprising, of course) the launched processes do not inherit the administrative privileges. The privileges are only granted with the "Modify" button.
![grafik](https://user-images.githubusercontent.com/15326471/62177222-709d0f00-b344-11e9-85a0-17925ce06d6b.png)
So either the installer itself manages the upla.ini modification or UpLa works with default mode 1 and gives the hint that the update mode may be changed via the System Control.

Just for completeness: Before I had detected all the implications, an attempt to reinstall Structorizer (for all users again) after having uninstalled it, consequently produced the following messages, because the javaw.exe processes had still been pending:
![ErrorOnReinstallation](https://user-images.githubusercontent.com/15326471/62168361-a8488e80-b325-11e9-8c2a-d8331844a252.png)
![ErrorOnReinstallation1](https://user-images.githubusercontent.com/15326471/62168371-abdc1580-b325-11e9-9772-67916937a1b9.png)

## Installation for the current account
An attempt to install the product for an individual account on Windows 7 resulted in a series of different errors:
![ErrorOnLocalInstallation](https://user-images.githubusercontent.com/15326471/62168705-7126ad00-b326-11e9-8218-5092bf252e38.png)
![ErrorOnLocalInstallation1](https://user-images.githubusercontent.com/15326471/62176044-43e6f880-b340-11e9-99dc-26ab9849e6b3.png)
![ErrorOnLocalInstallation2](https://user-images.githubusercontent.com/15326471/62176045-4a757000-b340-11e9-918c-afebeea2a7b1.png)
![ErrorOnLocalInstallation3](https://user-images.githubusercontent.com/15326471/62176052-506b5100-b340-11e9-88a0-6f07f9238f0d.png)

Obviously, HKEY_CLASSES_ROOT registry changes are not allowed with "normal" user privilege level. If I am not completely wrong, registry paths HKEY_CURRENT_USER/Software/ and HKEY_CURRENT_USER/Software/Classes would have to be set instead for installation in the individual environment. 
On the other hand, after repeated "Ignore and continue" choices, the initial update mode setting worked here (because upla.ini isn't protected), as well as the start of Structorizer (because the path didn't contain whitespace in this case).

**Comment by codemanyak** [comment]
I wrote:
> So either the installer itself manages the upla.ini modification or UpLa works with default mode 1 and gives the hint that the update mode may be changed via the System Control.

A possibility could be to provide three versions of upla.ini, which differ only by their updateMode number, to integrate a similar choice as in UpLa modification mode into the installation assistant and then copy the respective upla.ini version for the selected option. The ini files are small, so they wouldn't add substantially to the weight. This would work with both installation targets.

**Comment by fesch** [comment]
I was focusing too much in the administrative installation ;)

Fortunately Inno Setup has some more features I read about this morning. So what I have changed now:
- File types are registered either to HKCU or HKLM into "Software\Classes". This works now in both installation modes.
-  Update settings have to bee chosen inside installer, which chooses, as proposed, the right INI file to be copied.
![image](https://user-images.githubusercontent.com/1027354/62188300-3ba4b280-b36c-11e9-88c9-3d88647ee95e.png)

**Comment by codemanyak** [comment]
Looks a little different from what I had expected but at least works :-)
I got once a strange and discomforting message after having changed the update mode via the Modify button from "Programs and Features" (all users), saying that the uninstallation may not have been complete. But all files had still been in place and worked. I haven't managed to reproduce this effect, though.
So many thanks for all your efforts and the great result! (Though I will still do some further testing.)
